# Purpose: Write and visualize PDB file
# Author: Kevin Zhu
# Date: 11.14.2023
# Version: 1.0.0
# Bugs and Issues: N/A

#' Write Transformed Coordinates to PDB File
#'
#' This function writes the transformed coordinates obtained from a structure
#' alignment to a new PDB file. The transformed coordinates are generated by
#' applying the alignment parameters to the original coordinates of the second
#' protein structure. The resulting PDB file includes the transformed
#' coordinates alongside the original coordinates of the first structure.
#'
#' @param alignment List. Structure alignment results, including alignment
#'  parameters and transformed coordinates.
#'   The list should contain the following elements:\cr
#'   - coord1: 3D coordinates (matrix) of CA atoms for common residues in the
#'      first structure.\cr
#'   - coord2: 3D coordinates (matrix) of CA atoms for common residues in the
#'      second structure.\cr
#'   - values: Numeric vector. Alignment parameters obtained from structure
#'    alignment.\cr
#'   - rmsd: Numeric. Root Mean Square Deviation (RMSD) between the two protein
#'    structures.
#' @param outputfile Character. The name of the output PDB file to be created
#'  (default: "out.pdb").
#' @param appended Logical. If TRUE, the transformed coordinates are appended to
#'  the original coordinates
#'   in the output PDB file. If FALSE, the output PDB file contains only the
#'    transformed coordinates.
#' @param pdb1 Character. Path to the PDB file of the first protein structure.
#' @param pdb2 Character. Path to the PDB file of the second protein structure.
#' @param chain_1 Character. Chain identifier for the first protein structure in
#'  output file.
#' @param chain_2 Character. Chain identifier for the second protein structure
#'  in output file.
#'
#' @examples
#' \dontrun{
#' # Example: Write transformed coordinates to a new PDB file
#' pdb_file1 <- system.file("extdata", "1LNIA_decoy1_4.pdb",
#'                           package="TMscoreAlign"
#'                           )
#' pdb_file2 <- system.file("extdata", "1LNIA_decoy2_180.pdb",
#'                           package="TMscoreAlign"
#'                           )
#' alignment_results <- get_alignment(pdb_file1, pdb_file2,
#'                                     chain1 = 'A', chain2 = 'A',
#'                                     method = "alignment"
#'                                     )
#' write_pdb(alignment_results, outputfile = "aligned_structure.pdb",
#'          appended = TRUE, pdb1 = pdb_file1, pdb2 = pdb_file2,
#'          chain_1 = 'A', chain_2 = 'A'
#'          )
#' }
#'
#' @references
#' Berman, H., Henrick, K. and Nakamura, H.
#' Announcing the worldwide Protein Data Bank.
#' \emph{Nature Structural & Molecular Biology}, 10, 980 (2003).
#' \href{https://doi.org/10.1038/nsb1203-980}{Link}
#'
#' @seealso
#' \code{\link{get_alignment}} for obtaining structural alignment between two
#'   protein structures.
#' \code{\link{get_matrix}} for obtaining the transformation matrix from
#'   alignment parameters.
#'
#' @export
write_pdb <- function(alignment, outputfile = "out.pdb", appended = TRUE,
                      pdb1, pdb2, chain_1, chain_2
                      ) {

  values <- alignment$values
  matrix <- get_matrix(values)
  # browser()

  out <- file(outputfile, "w")
  atomid <- 1

  if (appended) {
    # Process the first PDB file
    lines <- readLines(pdb1)
    for (line in lines) {
      if (!grepl("^ATOM", line) || (substring(line, 22, 22) != " " &&
                                    substring(line, 22, 22) != chain_1
                                    )
          ) {
        next
      }
      cat(substr(line, 1, 6), sprintf("%4d", atomid), substr(line, 13, 20), "A",
          substr(line, 24, nchar(line)), "\n", file = out
          )
      atomid <- atomid + 1
    }
  }

  # Process the second PDB file
  lines <- readLines(pdb2)
  for (line in lines) {
    if (!grepl("^ATOM", line) || (substring(line, 22, 22) != " " &&
                                  substring(line, 22, 22) != chain_2
                                  )
        ) {
      next
      }

    x <- as.numeric(substr(line, 32, 38))
    y <- as.numeric(substr(line, 39, 46))
    z <- as.numeric(substr(line, 48, 54))

    vec <- c(x, y, z, 1)
    transformed_vec <- matrix %*% vec

    cat(substr(line, 1, 6), sprintf("%4d", atomid), substr(line, 13, 20), "B",
        substr(line, 24, 29),
        sprintf("%8.3f%8.3f%8.3f", transformed_vec[1], transformed_vec[2],
                transformed_vec[3]
                ),
        substr(line, 56, nchar(line)), "\n", file = out
        )
    atomid <- atomid + 1
  }

  close(out)
}

#' Visualize Protein Structure Alignment Using 3Dmol
#'
#' This function visualizes the structural alignment of two protein structures
#' by displaying the aligned coordinates in a 3D viewer. The viewer is set up
#' using 3Dmol, and the alignment is represented by color-coded cartoon-style
#' structures for each protein chain.
#'
#' @param alignment_pdb Character. Path to the PDB file containing the aligned
#'  coordinates. The PDB file should include both the original and
#'  transformed coordinates of the protein structures.
#' @param chain1 Character. Color code (hexadecimal) for the first protein
#'  structure (default: "#636efa").
#' @param chain2 Character. Color code (hexadecimal) for the second protein
#'  structure (default: "#ff7f0e").
#' @return A 3Dmol viewer displaying the aligned protein structures.
#'
#' @examples
#' \dontrun{
#' # Example: Visualize protein structure alignment
#' alignment_pdb_file <- "aligned_structure.pdb"
#' chain1_color <- "#636efa"  # Blue
#' chain2_color <- "#ff7f0e"  # Orange
#' visualize_alignment_pdb(alignment_pdb_file, chain1 = chain1_color,
#'                         chain2 = chain2_color
#'                         )
#' }
#'
#' @references
#' Su W, Johnston B (2021). r3dmol: Create Interactive 3D Visualizations of
#' Molecular Data. R package version 0.1.2.
#' \href{https://CRAN.R-project.org/package=r3dmol}{Link}.
#'
#' @seealso
#' \code{\link{write_pdb}} for generating a PDB file with transformed
#'   coordinates.
#' \code{\link{get_alignment}} for obtaining structural alignment between two
#'   protein structures.
#'
#' @export
#' @import r3dmol
visualize_alignment_pdb <- function(alignment_pdb = "out.pdb",
                                    chain1 = "#636efa", chain2 = "#ff7f0e") {
  r3dmol(                         # Set up the initial viewer
    viewer_spec = m_viewer_spec(
      cartoonQuality = 40,
      lowerZoomLimit = 50,
      upperZoomLimit = 350
    )
  ) %>%
    m_add_model(                  # Add model to scene
      data = alignment_pdb,
      format = "pdb"
    ) %>%
    m_zoom_to() %>%               # Zoom to encompass the whole scene
    m_set_style(                  # Style the first chain
      sel = m_sel(chain = "A"),
      style = m_style_cartoon(
        color = chain1,
        arrows = TRUE
      )
    ) %>%
    m_set_style(                  # Style the second chain
      sel = m_sel(chain = "B"),
      style = m_style_cartoon(
        color = chain2,
        arrows = TRUE
      )
    ) %>%
    m_rotate(                     # Rotate the scene
      angle = 90,
      axis = "y"
    ) %>%
    m_spin()                      # Animate the chains by spinning them
}
